spring:
  application:
    name: aws-test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://testdb1.cri44kk86bwv.ap-northeast-2.rds.amazonaws.com:3306/db1?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: admin
    password: max56685668!
  jpa:
    hibernate:
      # ?? JPA ??? ??? ?? ???
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect